app:
  name: 'app'
  version: '0.0.1'

http:
  port: ':3000'

logger:
  log_level: 'debug'

mongo:
  host: '127.0.0.1'
  user: 'user'
  dbName: 'dbname'
  password: 'password'
  options:
    minConnections: 10
    maxConnections: 100

jwt:
  secret: 'secret'
