version: '3'
services:
  db:
    image: mysql:8.3
    container_name: mysql-ms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
    platform: linux/arm64
    networks:
      - backend

networks:
  backend:
